# Generated by Django 4.1.3 on 2022-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_imageinfo_result_alter_imageinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='cc_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
